# Generated by Django 3.1.3 on 2021-12-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='passWord',
            field=models.CharField(max_length=128),
        ),
    ]
