# Generated by Django 3.1.3 on 2021-12-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='stu_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='stu_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='loginuser',
            name='stu_school',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
