# Generated by Django 3.1.3 on 2021-12-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211223_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
