# Generated by Django 3.1.3 on 2021-12-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20211226_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='stu_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='stu_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='loginuser',
            name='stu_school',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
