# Generated by Django 3.1.3 on 2021-12-25 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_loginuser_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginuser',
            old_name='passWord',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='loginuser',
            old_name='userName',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='loginuser',
            name='type',
        ),
    ]
