# Generated by Django 3.1.3 on 2021-12-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0007_auto_20211226_0959'),
        ('login', '0004_auto_20211225_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='banji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='classpage.banji'),
        ),
    ]
