# Generated by Django 3.1.3 on 2021-12-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_loginuser_banji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginuser',
            name='banji',
        ),
    ]
