# Generated by Django 3.1.3 on 2021-12-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_loginuser_banji'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginuser',
            name='banid',
            field=models.IntegerField(default=-1),
        ),
    ]
