# Generated by Django 3.1.3 on 2021-12-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_auto_20211226_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginuser',
            name='stu_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
