# Generated by Django 3.1.3 on 2021-12-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0004_auto_20211225_1211'),
    ]

    operations = [
        migrations.CreateModel(
            name='banji',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('year', models.IntegerField(max_length=4)),
                ('season', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('simple_name', models.CharField(max_length=16)),
                ('type', models.CharField(max_length=20)),
                ('banji', models.ManyToManyField(blank=True, related_name='course', to='classpage.banji')),
                ('user', models.ManyToManyField(blank=True, related_name='course', to='login.loginUser')),
            ],
        ),
    ]
