# Generated by Django 3.1.3 on 2021-12-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211225_1211'),
        ('classpage', '0002_auto_20211225_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='user',
            field=models.ManyToManyField(blank=True, related_name='course', to='login.loginUser'),
        ),
    ]
