# Generated by Django 3.1.3 on 2021-12-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0002_remove_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='banji',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
