# Generated by Django 3.1.3 on 2021-12-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0003_banji_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='banji',
            name='num',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
