# Generated by Django 3.1.3 on 2021-12-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0003_auto_20211225_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
