# Generated by Django 3.1.3 on 2021-12-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20211225_1211'),
        ('classpage', '0004_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='user',
        ),
        migrations.AddField(
            model_name='banji',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banji', to='login.loginuser'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='banji',
        ),
        migrations.AddField(
            model_name='course',
            name='banji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='classpage.banji'),
        ),
    ]
