# Generated by Django 3.1.3 on 2021-12-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0004_banji_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banji',
            name='num',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
