# Generated by Django 3.1.3 on 2021-12-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0005_auto_20211227_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banji',
            name='color',
            field=models.CharField(blank=True, choices=[('color0', 'style0'), ('color1', 'style1'), ('color2', 'style2'), ('color3', 'style3')], max_length=50),
        ),
    ]
