# Generated by Django 3.1.3 on 2021-12-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0005_auto_20211226_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='banji',
            name='course_id',
            field=models.IntegerField(default=-1),
        ),
    ]
