# Generated by Django 3.1.3 on 2021-12-27 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_loginuser_banji'),
        ('classpage', '0006_auto_20211227_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='banji',
            name='user',
            field=models.ManyToManyField(related_name='banji', to='login.loginUser'),
        ),
    ]
