# Generated by Django 3.1.3 on 2021-12-26 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0006_banji_course_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banji',
            old_name='course_id',
            new_name='couid',
        ),
        migrations.RemoveField(
            model_name='banji',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course',
            name='banji',
        ),
        migrations.AddField(
            model_name='banji',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='banji', to='classpage.course'),
        ),
    ]
