# Generated by Django 3.1.3 on 2021-12-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classpage', '0007_banji_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banji',
            old_name='user',
            new_name='student',
        ),
    ]
