# Generated by Django 3.1.3 on 2021-12-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_remove_loginuser_banji'),
        ('classpage', '0009_banji_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banji',
            name='color',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='banji',
            name='student',
            field=models.ManyToManyField(blank=True, related_name='banji', to='login.loginUser'),
        ),
    ]
